"""Commerce enums."""
from enum import StrEnum
class ApprovalStatus(StrEnum): PENDING="PENDING"; APPROVED="APPROVED"; REJECTED="REJECTED"; EXPIRED="EXPIRED"
class TrustLevel(StrEnum): UNTRUSTED_DATA="UNTRUSTED_DATA"; TOOL_RESPONSE="TOOL_RESPONSE"; TRUSTED_POLICY="TRUSTED_POLICY"
